import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000');await p.waitForFunction(()=>window.Journey?.getState().sceneReady);await p.locator('[data-route="futurist"]').click();assert.equal(await p.locator('.trail-node').count(),6);
const initial=await p.evaluate(()=>Journey.getState().avatar);assert.equal(initial.adult,false);assert.equal(initial.biologicalRightArm,true);
for(let i=0;i<6;i++){
 await p.locator('#approach').click();await p.locator('#encounter').waitFor({state:'visible',timeout:60000});assert.equal(await p.locator('[data-answer]').count(),0);assert.equal(await p.locator('#integrate').isDisabled(),true);
 await p.locator('#preview-body').click();const preview=await p.evaluate(()=>Journey.getState());assert.equal(preview.previewing,true);assert.equal(preview.paths.futurist.length,i);if(i===0){assert.equal(preview.avatar.biologicalRightArm,false);assert.deepEqual(preview.acquired,[]);}await p.locator('#preview-body').click();assert.equal(await p.evaluate(()=>Journey.getState().previewing),false);
 if(i===3)await p.locator('#decline').click();else{await p.locator('#understand-limit').check();await p.locator('#integrate').click();}
 const state=await p.evaluate(()=>Journey.getState());if(i===0)assert.equal(state.avatar.biologicalRightArm,false);if(i>=1){assert.ok(state.acquired.includes('arm'));assert.ok(state.acquired.includes('neural'));}if(i===3)assert.ok(!state.acquired.includes('senses'));
 if(i===1)await p.screenshot({path:'evolution-arm-neural.png'});await p.locator('#continue-path').click();
}
assert.equal(await p.locator('#chapter-end').isVisible(),true);assert.match(await p.locator('#chapter-end').textContent(),/Level 5/);assert.match(await p.locator('#chapter-end').textContent(),/Declined/);const adult=await p.evaluate(()=>Journey.getState().avatar);assert.equal(adult.adult,true);assert.ok(adult.headHeight>initial.headHeight+1);assert.deepEqual(adult.modules.sort(),['arm','exo','heart','neural']);await p.locator('[data-close-end]').first().click();await p.locator('#recenter').click();await p.screenshot({path:'evolution-adult-desktop.png'});
await p.reload();await p.waitForFunction(()=>window.Journey?.getState().sceneReady);assert.deepEqual((await p.evaluate(()=>Journey.getState().avatar.modules)).sort(),['arm','exo','heart','neural']);assert.equal(await p.evaluate(()=>Journey.getState().avatar.adult),true);
await p.setViewportSize({width:390,height:844});await p.locator('[data-encounter="0"]').click();await p.locator('#encounter').waitFor({state:'visible'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'evolution-mobile.png'});await p.locator('[data-close-encounter]').click();assert.deepEqual(errors,[]);console.log('PASS: no quizzes, six Future capability encounters, preview rollback, consent gating, actual arm replacement, cumulative neural/organ/exoskeleton modules, declined senses absent, child-to-adult proportions, independent ending, save/reload, mobile body lab.');
}finally{await b.close()}
