import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});
try{
const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],calls=[];p.on('pageerror',e=>errors.push(e.message));
const uid='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',user={id:uid,aud:'authenticated',role:'authenticated',email:'explorer@example.test',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email',providers:['email']},user_metadata:{display_name:'Test Explorer'},created_at:new Date().toISOString()};const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const token=enc({alg:'HS256',typ:'JWT'})+'.'+enc({sub:uid,aud:'authenticated',role:'authenticated',exp:Math.floor(Date.now()/1000)+3600,iat:Math.floor(Date.now()/1000)})+'.mock';const session={access_token:token,refresh_token:'mock-refresh-token',expires_in:3600,token_type:'bearer',user};let rejectLogin=true;
await p.route('**/auth/v1/**',async r=>{const url=new URL(r.request().url());calls.push({path:url.pathname,query:url.search,body:r.request().postDataJSON(),headers:r.request().headers()});let data={},status=200;if(url.pathname.endsWith('/signup'))data={user,session:null};else if(url.pathname.endsWith('/token')){if(url.searchParams.get('grant_type')==='password'&&rejectLogin){status=400;data={code:'invalid_credentials',msg:'Invalid login credentials'};}else data=session;}else if(url.pathname.endsWith('/user'))data=user;await r.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});});
await p.goto('http://localhost:3000/login.html');await p.waitForFunction(()=>!document.querySelector('#auth-submit').disabled);await p.screenshot({path:'account-signin-desktop.png'});
await p.locator('[data-mode="signup"]').click();await p.locator('#auth-name').fill('Test Explorer');await p.locator('#auth-email').fill(user.email);await p.locator('#auth-password').fill('a-strong-test-password');await p.locator('#show-password').click();assert.equal(await p.locator('#auth-password').getAttribute('type'),'text');await p.locator('#auth-submit').click();await p.waitForFunction(()=>!document.querySelector('#auth-submit').disabled);assert.match(await p.locator('#auth-status').textContent(),/confirmation link/);assert.equal(await p.locator('#auth-password').inputValue(),'');const signup=calls.find(c=>c.path.endsWith('/signup'));assert.equal(signup.body.data.display_name,'Test Explorer');assert.ok(signup.query.includes('redirect_to='));assert.equal(signup.body.password,'a-strong-test-password');
await p.locator('#auth-email').fill(user.email);await p.locator('#auth-password').fill('wrong-test-password');await p.locator('#auth-submit').click();await p.waitForFunction(()=>!document.querySelector('#auth-submit').disabled);assert.match(await p.locator('#auth-status').textContent(),/not accepted/);rejectLogin=false;await p.locator('#auth-password').fill('a-strong-test-password');await p.locator('#auth-submit').click();await p.locator('#account-panel').waitFor({state:'visible'});assert.equal(await p.locator('#account-email').textContent(),user.email);await p.evaluate(()=>localStorage.setItem('continuum-journey-v2','{"route":null,"paths":{}}'));await p.reload();await p.locator('#account-panel').waitFor({state:'visible'});await p.locator('#signout').click();await p.waitForFunction(()=>!document.querySelector('#auth-submit').disabled);assert.equal(await p.locator('#auth-form').isVisible(),true);assert.equal(await p.evaluate(()=>localStorage.getItem('continuum-journey-v2')),'{"route":null,"paths":{}}');
await p.locator('#forgot-password').click();await p.locator('#auth-email').fill(user.email);await p.locator('#auth-submit').click();await p.waitForFunction(()=>!document.querySelector('#auth-submit').disabled);assert.match(await p.locator('#auth-status').textContent(),/If an account exists/);assert.ok(calls.some(c=>c.path.endsWith('/recover')&&c.query.includes('mode%3Dreset')));
await p.goto('http://localhost:3000/login.html?mode=reset&code=mock-recovery-code');await p.waitForFunction(()=>document.querySelector('#auth-title').textContent==='Choose a new password.');await p.locator('#auth-password').fill('new-strong-test-password');await p.locator('#auth-submit').click();await p.locator('#account-panel').waitFor({state:'visible'});assert.ok(calls.some(c=>c.path.endsWith('/user')&&c.body?.password==='new-strong-test-password'));await p.locator('#signout').click();await p.waitForFunction(()=>!document.querySelector('#auth-submit').disabled);
for(const width of [390,320]){await p.setViewportSize({width,height:844});await p.locator('[data-mode="signup"]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`account-signup-mobile-${width}.png`,fullPage:true});}
await p.goto('http://localhost:3000/login.html#error=access_denied&error_description=expired');await p.waitForFunction(()=>document.querySelector('#auth-status').textContent.includes('expired'));assert.equal(await p.evaluate(()=>location.hash),'');
await p.goto('http://localhost:3000');await p.locator('.account-link').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.goto('http://localhost:3000/atlas.html');assert.equal(await p.locator('.account-link').textContent(),'Sign in');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
for(const c of calls){const api=c.headers.apikey;if(api?.startsWith('ey'))assert.equal(JSON.parse(Buffer.from(api.split('.')[1],'base64url')).role,'anon');}assert.deepEqual(errors,[]);console.log('PASS (mocked Auth transport): sign-up confirmation, validation, failed/successful sign-in, verified account reload, device sign-out preserving journey, PKCE recovery and password update, expired links, 320/390 layouts, header entries, public anon key only. No real accounts or emails created.');
}finally{await b.close()}
