import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({args:['--no-sandbox']});
try{
 const page=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000/atlas.html');await page.locator('#path-button').click();await page.locator('button[data-pathway="philosopher"]').click();await page.locator('#domain-tabs [data-domain="ethics"]').click();
 await page.waitForFunction(()=>document.querySelector('.human').complete&&document.querySelector('.human').naturalHeight>0);
 async function geometry(){return page.evaluate(()=>{const box=sel=>{const r=document.querySelector(sel).getBoundingClientRect();return {left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};return {image:box('.human'),viewport:box('#avatar-viewport'),workspace:box('.workspace'),canvas:box('#canvas'),tools:box('.canvas-tools'),mask:getComputedStyle(document.querySelector('.human')).maskImage,state:AvatarViewer.getState()};});}
 function fullBody(g){assert.ok(g.image.left>=g.viewport.left-.5);assert.ok(g.image.right<=g.viewport.right+.5);assert.ok(g.image.top>=g.viewport.top-.5);assert.ok(g.image.bottom<=g.viewport.bottom+.5);assert.equal(g.mask,'none');assert.ok(g.tools.bottom<=g.workspace.bottom);assert.ok(g.tools.top>=g.canvas.top);}
 fullBody(await geometry());await page.screenshot({path:'body-view-ethics.png',animations:'disabled'});
 await page.locator('.ethics-node[data-topic="Consent"]').click();await page.locator('#zoom-in').click();assert.equal(await page.locator('#zoom-label').textContent(),'125%');assert.equal(await page.locator('.ethics-node').first().isVisible(),true);assert.equal(await page.locator('.detail h2').textContent(),'Consent');assert.equal(await page.locator('#inspect-body').textContent(),'Inspect body');
 for(let i=0;i<7;i++)await page.locator('#zoom-in').click();assert.equal(await page.locator('#zoom-label').textContent(),'300%');assert.equal(await page.locator('#zoom-in').isDisabled(),true);
 let g=await geometry();const x=g.viewport.left+g.viewport.width/2,y=g.viewport.top+g.viewport.height/2;
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y+110,{steps:5});await page.mouse.up();assert.ok((await geometry()).state.y>80);
 await page.locator('#fit').click();fullBody(await geometry());assert.equal((await geometry()).state.y,0);assert.equal(await page.locator('#zoom-label').textContent(),'100%');assert.equal(await page.locator('.detail h2').textContent(),'Consent');await page.screenshot({path:'body-view-full-fit.png',animations:'disabled'});
 await page.locator('#inspect-body').click();assert.equal(await page.locator('.ethics-node').first().isVisible(),false);await page.locator('#inspect-body').click();assert.equal(await page.locator('.ethics-node').first().isVisible(),true);
 await page.locator('#zoom-out').click();assert.equal(await page.locator('#zoom-label').textContent(),'75%');await page.locator('#zoom-out').click();assert.equal(await page.locator('#zoom-label').textContent(),'50%');assert.equal(await page.locator('#zoom-out').isDisabled(),true);fullBody(await geometry());
 await page.locator('#fit').click();g=await geometry();await page.mouse.move(g.viewport.left+g.viewport.width/2,g.viewport.top+g.viewport.height/2);await page.mouse.wheel(0,-240);assert.ok((await geometry()).state.zoom>150);await page.locator('#avatar-viewport').press('0');assert.equal(await page.locator('#zoom-label').textContent(),'100%');await page.locator('#avatar-viewport').press('+');assert.equal(await page.locator('#zoom-label').textContent(),'125%');await page.locator('#reset').click();assert.equal(await page.locator('#inspect-body').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('.detail h2').textContent(),'Consent');
 for(const size of [{width:1024,height:768},{width:800,height:760},{width:768,height:650},{width:390,height:844},{width:320,height:740}]){
  await page.setViewportSize(size);await page.locator('#fit').click();await page.waitForFunction(()=>Math.abs(document.querySelector('.human').getBoundingClientRect().width-AvatarViewer.getState().width)<1);fullBody(await geometry());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.locator('#zoom-in').click();assert.equal(await page.locator('#zoom-label').textContent(),'125%');await page.locator('#fit').click();fullBody(await geometry());
  if(size.width===800)await page.screenshot({path:'body-view-tablet.png',animations:'disabled'});
 }
 await page.setViewportSize({width:390,height:844});await page.locator('#fit').click();await page.locator('#zoom-in').click();await page.locator('#zoom-out').click();await page.locator('#avatar-viewport').scrollIntoViewIfNeeded();g=await geometry();
 const client=await page.context().newCDPSession(page);const cx=g.viewport.left+g.viewport.width/2,cy=g.viewport.top+g.viewport.height/2;
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy-35,id:1},{x:cx,y:cy+35,id:2}]});
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx,y:cy-65,id:1},{x:cx,y:cy+65,id:2}]});
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok((await geometry()).state.zoom>150,'Two-finger pinch changes model zoom');assert.equal(await page.locator('.ethics-node').first().isVisible(),true);await page.locator('#fit').click();fullBody(await geometry());await page.screenshot({path:'body-view-mobile.png',animations:'disabled'});
 await page.locator('#domain-tabs [data-domain="identity-problem"]').click();assert.equal(await page.locator('#inspect-body').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('.identity-step').count(),7);fullBody(await geometry());assert.deepEqual(errors,[]);
 console.log('PASS: complete head-to-feet fit, no radial mask, accessible toolbars at desktop/tablet/mobile sizes, 50–300% buttons and limits, wheel, keyboard, mouse panning, real touch pinch, reset/fit recentering, unobstructed inspection mode, topic/selection preservation, resize handling. No JS errors.');
}finally{await b.close()}
