import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const b=await chromium.launch({args:['--no-sandbox']});
try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));let payload;
 await p.goto('http://localhost:3000/atlas.html');await p.evaluate(()=>{localStorage.setItem('continuum-visited',JSON.stringify(['cells:DNA','identity-you:Replace your arm']));localStorage.setItem('continuum-reflections',JSON.stringify({'Replace your arm':'same'}));localStorage.removeItem('continuum-ethics-reflections')});await p.reload();
 await p.locator('#path-button').click();await p.locator('button[data-pathway="philosopher"]').click();assert.equal(await p.locator('#domain-tabs button').count(),3);assert.equal(await p.locator('#knowledge-sections [data-domain="ethics"]').count(),1);assert.equal(await p.locator('#progress-count').textContent(),'1 / 24');
 await p.locator('#knowledge-sections [data-domain="ethics"]').click();assert.equal(await p.locator('h1').textContent(),'Possible. But permissible?');assert.equal(await p.locator('.ethics-node').count(),11);assert.equal(await p.locator('.detail h2').textContent(),'Ethics');
 const topics=await p.evaluate(()=>ETHICS_TOPICS.map(t=>t.name));const sources=new Set(),artworks=new Set();
 for(const topic of topics){
  await p.locator(`.ethics-node[data-topic="${topic}"]`).click();assert.equal(await p.locator('.detail h2').textContent(),topic);await p.waitForFunction(()=>document.querySelector('.detail-art img').complete&&document.querySelector('.detail-art img').naturalWidth>0);
  const src=await p.locator('.detail-art img').getAttribute('src');sources.add(src);artworks.add(fs.readFileSync('public/'+src.replace('./',''),'utf8').replace(/<title.*?<\/title>|<desc.*?<\/desc>/g,''));
  assert.equal(await p.locator('#canvas img:not(.human)').count(),0);assert.equal(await p.locator('#focus-visual').count(),0);assert.equal(await p.locator('.ethics-node.active').getAttribute('data-topic'),topic);assert.equal(await p.locator('[data-ethics-choice]').count(),4);assert.match(await p.locator('#chat-context').textContent(),/The Philosopher \/ Ethics/);
  await p.locator('[data-ethics-choice]').first().click();assert.equal(await p.locator('[data-ethics-choice]').first().getAttribute('aria-pressed'),'true');
 }
 assert.equal(sources.size,11);assert.equal(artworks.size,11);assert.equal(await p.locator('#progress-count').textContent(),'12 / 24');
 await p.locator('.ethics-node[data-topic="Who gets access?"]').click();await p.screenshot({path:'ethics-desktop.png',animations:'disabled'});
 await p.locator('.ethics-node[data-topic="Consent"]').click();await p.locator('#ethics-note').fill('PRIVATE_LOCAL_NOTE <img src=x onerror=alert(1)>');await p.locator('.related [data-topic="Ownership of biological information"]').click();assert.equal(await p.locator('.detail h2').textContent(),'Ownership of biological information');await p.locator('#branch-overview').click();assert.equal(await p.locator('.detail h2').textContent(),'Ethics');
 await p.locator('#domain-tabs [data-domain="identity-problem"]').click();await p.locator('.identity-step').first().click();assert.equal(await p.locator('[data-reflection="same"]').getAttribute('aria-pressed'),'true');await p.locator('[data-open-analysis]').click();assert.match(await p.locator('.pattern-lead').textContent(),/all 1 answered steps/);await p.locator('#close-modal').click();
 await p.locator('#domain-tabs [data-domain="ethics"]').click();await p.locator('.ethics-node[data-topic="Consent"]').click();assert.match(await p.locator('#ethics-note').inputValue(),/PRIVATE_LOCAL_NOTE/);assert.equal(await p.locator('#detail img').count(),1);
 await p.route('**/*atlas_api=chat*',async r=>{payload=r.request().postDataJSON();await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({text:'A mock ethical discussion.'})})});await p.locator('#explore-detail').click();await p.locator('#chat-form button').click();await p.waitForFunction(()=>!document.querySelector('#chat-form button').disabled);assert.match(payload.context,/ethical inquiry/);assert.match(payload.context,/earlier choice/);assert.ok(!JSON.stringify(payload).includes('PRIVATE_LOCAL_NOTE'));assert.ok(!payload.context.includes('numerical personal identity'));await p.locator('#close-chat').click();
 for(const width of [390,320]){
  await p.setViewportSize({width,height:844});await p.locator('#domain-tabs [data-domain="ethics"]').click();await p.locator('.ethics-node[data-topic="Ownership of biological information"]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('h1').scrollIntoViewIfNeeded();await p.screenshot({path:`ethics-mobile-${width}.png`,animations:'disabled'});
 }
 await p.reload();await p.locator('#workspace-path-button').click();await p.locator('button[data-pathway="philosopher"]').click();await p.locator('#domain-tabs [data-domain="ethics"]').click();await p.locator('.ethics-node[data-topic="Consent"]').click();assert.match(await p.locator('#ethics-note').inputValue(),/PRIVATE_LOCAL_NOTE/);assert.equal(await p.locator('[data-ethics-choice]').first().getAttribute('aria-pressed'),'true');
 await p.locator('#journey').click();assert.match(await p.locator('#modal-content').textContent(),/13 of 141/);assert.match(await p.locator('#modal-content').textContent(),/Ethics/);assert.deepEqual(errors,[]);
 console.log('PASS: 11 unique Ethics illustrations, side-panel only, 11 non-sequential map topics, separate saved ethics stances and notes, identity analysis retained, related navigation, source/overview rendering, ethics chat context with private notes excluded, 390px/320px layouts, total 141 concepts. No JS errors.');
}finally{await b.close()}
