import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const browser=await chromium.launch({args:['--no-sandbox']});
try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:3000/atlas.html');await p.evaluate(()=>{localStorage.setItem('continuum-visited',JSON.stringify(['cells:DNA','identity-you:Replace your arm','ethics-questions:Consent']));localStorage.setItem('continuum-reflections',JSON.stringify({'Replace your arm':'same'}));localStorage.setItem('continuum-ethics-reflections',JSON.stringify({Consent:{choice:'renewal',note:'PRIVATE EXISTING NOTE'}}))});await p.reload();
 await p.locator('#path-button').click();assert.equal(await p.locator('button[data-pathway]').count(),3);assert.equal(await p.locator('button[data-pathway="futurist"]').isEnabled(),true);await p.locator('button[data-pathway="futurist"]').click();
 assert.equal(await p.locator('#domain-tabs button').count(),4);assert.equal(await p.locator('#progress-count').textContent(),'0 / 46');assert.match(await p.locator('.progress').textContent(),/FUTURIST EXPLORATION/);
 const data=await p.evaluate(()=>({domains:ATLAS_DOMAINS.filter(d=>d.pathway==='futurist').map(d=>({id:d.id,count:topicCount(branches(d))})),branches:FUTURIST_BRANCHES.map(b=>({id:b.id,name:b.name,domain:b.domain,items:b.items})),total:totalTopics,related:FUTURIST_BRANCHES.every(b=>b.related.every(id=>ATLAS.some(a=>a.id===id)))}));
 assert.deepEqual(data.domains.map(d=>d.count),[9,4,8,25]);assert.equal(data.total,141);assert.equal(data.related,true);assert.deepEqual(data.branches.filter(b=>b.domain==='longevity-technology').map(b=>b.items.length),[4,4,4,5,4,4]);
 const sources=new Set(),shapes=new Set(),duplicates=[];
 for(const branch of data.branches){
  await p.locator(`#domain-tabs [data-domain="${branch.domain}"]`).click();
  if(branch.domain==='longevity-technology'){assert.equal(await p.locator('.futurist-node').count(),6);await p.locator(`.futurist-node[data-category="${branch.id}"]`).click();}else assert.equal(await p.locator('.futurist-node').count(),branch.items.length);
  assert.equal(await p.locator('.ft-topic-list button').count(),branch.items.length);
  for(const topic of branch.items){
   await p.locator(`#detail .ft-topic-list [data-topic="${topic.name}"]`).click();assert.equal(await p.locator('#detail h2').textContent(),topic.name);assert.match(await p.locator('.ft-limit').textContent(),/WHAT THIS DOES NOT ESTABLISH/);assert.equal(await p.locator('.ethical-scenario h3').textContent(),topic.question);assert.equal(await p.locator('.readiness').count(),1);
   await p.waitForFunction(()=>{const img=document.querySelector('.detail-art img');return img.complete&&img.naturalWidth>0});
   const src=await p.locator('.detail-art img').getAttribute('src');sources.add(src);shapes.add(fs.readFileSync('public/'+src.replace('./','').split('?')[0],'utf8').replace(/<title.*?<\/title>|<desc.*?<\/desc>|<text.*?<\/text>/g,''));if(topic.name==='Artificial organs')duplicates.push(src);
   assert.equal(await p.locator('#canvas img:not(.human)').count(),0);assert.match(await p.locator('#chat-context').textContent(),/The Futurist/);assert.ok((await p.locator('#chat-context').textContent()).includes(topic.name));
   if(branch.domain==='digital-immortality')assert.match(await p.locator('.replica-notice').textContent(),/DIGITAL REPLICA ≠ ORIGINAL CONSCIOUSNESS/);
  }
 }
 assert.equal(sources.size,46);assert.equal(shapes.size,46);assert.equal(duplicates.length,2);assert.notEqual(duplicates[0],duplicates[1]);assert.equal(await p.locator('#progress-count').textContent(),'46 / 46');
 await p.locator('#domain-tabs [data-domain="digital-immortality"]').click();await p.locator('.futurist-node[data-topic="AI replica"]').click();await p.screenshot({path:'futurist-digital-desktop.png',animations:'disabled'});
 const before=await p.locator('.futurist-node').first().boundingBox();await p.locator('#zoom-in').click();await p.locator('#zoom-in').click();const after=await p.locator('.futurist-node').first().boundingBox();assert.ok(Math.abs(before.x-after.x)<1&&Math.abs(before.y-after.y)<1);assert.equal(await p.locator('.futurist-node').first().isVisible(),true);assert.equal(await p.locator('#inspect-body').getAttribute('aria-pressed'),'false');await p.locator('.futurist-node[data-topic="Whole-brain emulation"]').click();assert.equal(await p.locator('#zoom-label').textContent(),'150%');
 await p.locator('#inspect-body').click();assert.equal(await p.locator('.futurist-node').first().isVisible(),false);await p.locator('#inspect-body').click();assert.equal(await p.locator('.futurist-node').first().isVisible(),true);
 let payload;await p.route('**/*atlas_api=chat*',async r=>{payload=r.request().postDataJSON();await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({text:'A mocked evidence-focused response.'})})});await p.locator('#explore-detail').click();await p.locator('#chat-form button').click();await p.waitForFunction(()=>!document.querySelector('#chat-form button').disabled);assert.match(payload.context,/Whole-brain emulation/);assert.match(payload.context,/DIGITAL REPLICA ≠ ORIGINAL CONSCIOUSNESS/);assert.match(payload.context,/speculative/);assert.ok(!JSON.stringify(payload).includes('PRIVATE EXISTING NOTE'));await p.locator('#close-chat').click();
 await p.locator('[data-ft-ethics="Digital personhood"]').click();assert.equal(await p.locator('#detail h2').textContent(),'Digital personhood');await p.locator('#path-button').click();await p.locator('button[data-pathway="futurist"]').click();assert.equal(await p.locator('#detail h2').textContent(),'Whole-brain emulation');
 await p.locator('#domain-tabs [data-domain="longevity-technology"]').click();await p.locator('.futurist-node[data-category="fut-regenerative"]').click();await p.locator('#detail [data-topic="3D bioprinting"]').click();await p.screenshot({path:'futurist-longevity-desktop.png',animations:'disabled'});
 for(const width of [768,390,320]){
  await p.setViewportSize({width,height:844});
  for(const d of data.domains){await p.locator(`#domain-tabs [data-domain="${d.id}"]`).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const rects=await p.locator('.futurist-node').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return {l:r.left,r:r.right,t:r.top,b:r.bottom}}));for(let i=0;i<rects.length;i++){assert.ok(rects[i].l>=0&&rects[i].r<=width);for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j];assert.ok(a.r<=b.l||b.r<=a.l||a.b<=b.t||b.b<=a.t,'nodes must not overlap')}}await p.locator('.futurist-node').last().click();await p.locator('#zoom-in').click();assert.equal(await p.locator('.futurist-node').first().isVisible(),true);await p.locator('#fit').click();}
  await p.locator('h1').scrollIntoViewIfNeeded();await p.screenshot({path:`futurist-mobile-${width}.png`,animations:'disabled'});
 }
 await p.reload();await p.locator('#workspace-path-button').click();await p.locator('button[data-pathway="futurist"]').click();assert.equal(await p.locator('#progress-count').textContent(),'46 / 46');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('continuum-reflections'))['Replace your arm']),'same');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('continuum-ethics-reflections')).Consent.note),'PRIVATE EXISTING NOTE');
 await p.locator('#journey').click();assert.match(await p.locator('#modal-content').textContent(),/50 of 141/);assert.match(await p.locator('#modal-content').textContent(),/Longevity Technology/);assert.deepEqual(errors,[]);
 console.log('PASS: all 46 topics, four categories, exact six longevity branches, 46 distinct right-only diagrams, scoped repeated labels, explicit digital distinction, readiness and limits, persistent progress/reflections, cross-pathway links, contextual chat (mocked), stable zoom topics, explicit inspection, 768/390/320 geometry; no JS errors.');
}finally{await browser.close()}
