import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const b=await chromium.launch({args:['--no-sandbox']});
try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000/atlas.html');await p.evaluate(()=>localStorage.setItem('continuum-reflections',JSON.stringify({'Replace your arm':'same'})));
 const before=await p.locator('#progress-count').textContent();await p.locator('footer [data-open-levels]').click();assert.equal(await p.locator('#levels-dialog').isVisible(),true);assert.equal(await p.locator('.level-row').count(),6);
 const titles=['Normal human lifespan','Healthspan extension','Significant lifespan extension','Biological rejuvenation','Continuous organ replacement','Biological body + artificial systems'];assert.deepEqual(await p.evaluate(()=>IMMORTALITY_LEVELS.map(l=>l.title)),titles);assert.equal(await p.evaluate(()=>ATLAS_PATHWAYS.length),3);
 assert.ok(await p.evaluate(()=>IMMORTALITY_LEVELS.every(l=>l.links.every(x=>{const a=ATLAS.find(b=>b.id===x.branch);return a&&(!x.topic||Object.hasOwn(a.topics,x.topic))}))));
 const imgs=new Set(),art=new Set();for(let i=0;i<6;i++){await p.locator(`.level-row[data-level="${i}"]`).click();assert.equal(await p.locator('.level-lead h3').textContent(),titles[i]);await p.waitForFunction(()=>{const im=document.querySelector('.level-lead img');return im.complete&&im.naturalWidth>0});const src=await p.locator('.level-lead img').getAttribute('src');imgs.add(src);art.add(fs.readFileSync('public/'+src.replace('./','').split('?')[0],'utf8').replace(/<title.*?<\/title>|<desc.*?<\/desc>|<text.*?<\/text>/g,''));assert.match(await p.locator('.levels-principle').textContent(),/None establishes immortality/);assert.equal(await p.locator('.level-limit').count(),1);}
 assert.equal(imgs.size,6);assert.equal(art.size,6);assert.match(await p.locator('.levels-progress').textContent(),/6 \/ 6/);assert.equal(await p.locator('#progress-count').textContent(),before);assert.equal(await p.locator('.level-pagination button').last().isDisabled(),true);await p.screenshot({path:'immortality-levels-desktop.png',animations:'disabled'});
 let payload;await p.route('**/*atlas_api=chat*',async r=>{payload=r.request().postDataJSON();await r.fulfill({contentType:'application/json',body:JSON.stringify({text:'Mock evidence-focused discussion.'})})});await p.locator('[data-level-ask]').click();assert.equal(await p.locator('#levels-dialog').isVisible(),false);await p.locator('#chat-form button').click();await p.waitForFunction(()=>!document.querySelector('#chat-form button').disabled);assert.match(payload.context,/Standalone final framework/);assert.match(payload.context,/Biological body \+ artificial systems/);assert.ok(!payload.context.includes('Cells:'));await p.locator('#close-chat').click();
 await p.locator('footer [data-open-levels]').click();await p.locator('.level-row[data-level="4"]').click();await p.locator('[data-level-link="1"]').click();assert.equal(await p.locator('#detail h2').textContent(),'Artificial organs');assert.equal(await p.evaluate(()=>window.frameworkChatContext),null);
 for(const width of [390,320]){await p.setViewportSize({width,height:844});await p.locator('footer [data-open-levels]').click();await p.locator('.level-row[data-level="3"]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await p.locator('.level-panel').evaluate(e=>e.scrollWidth<=e.clientWidth));await p.screenshot({path:`immortality-levels-mobile-${width}.png`,animations:'disabled'});await p.keyboard.press('Escape');assert.equal(await p.locator('#levels-dialog').isVisible(),false);}
 await p.reload();await p.locator('footer [data-open-levels]').click();assert.match(await p.locator('.levels-progress').textContent(),/6 \/ 6/);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('continuum-reflections'))['Replace your arm']),'same');assert.deepEqual(errors,[]);console.log('PASS: standalone six-level framework, exact hierarchy, six distinct diagrams, working cross-pathway links, separate persisted progress, scoped chat (mocked), no stale framework context, 320/390 layouts, Escape close, no browser errors.');
}finally{await b.close()}
