import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000');await p.waitForFunction(()=>window.Journey?.getState().sceneReady);
 await p.evaluate(()=>{const paths=Object.fromEntries(Object.entries(JOURNEY_ROUTES).map(([id,r])=>[id,r.encounters.map(e=>({id:e.id,choice:0}))]));localStorage.setItem('continuum-journey-v2',JSON.stringify({route:'futurist',paths}));localStorage.setItem('continuum-visited','["cells:DNA"]');localStorage.setItem('continuum-reflections','{"Replace your arm":"same"}');});await p.reload();await p.waitForFunction(()=>Journey.getState().sceneReady);assert.equal(await p.evaluate(()=>Journey.getState().avatar.adult),true);
 await p.locator('#approach').click();await p.locator('#undo-pathway').click();await p.locator('#cancel-pathway-undo').click();assert.equal(await p.locator('#chapter-end').isVisible(),true);assert.equal(await p.evaluate(()=>Journey.getState().paths.futurist.length),6);
 await p.locator('#undo-pathway').click();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>Journey.getState().paths.futurist.length),6);
 await p.locator('#undo-pathway').click();await p.locator('#confirm-pathway-undo').click();const state=await p.evaluate(()=>Journey.getState());assert.equal(state.route,null);assert.equal(state.avatar.growth,0);assert.equal(state.avatar.adult,false);assert.deepEqual(state.avatar.modules,[]);assert.equal(state.avatar.biologicalRightArm,true);assert.equal(state.paths.futurist,undefined);assert.equal(state.paths.scientist.length,5);assert.equal(state.paths.philosopher.length,3);assert.match(await p.locator('[data-route="futurist"]').textContent(),/Enter the unknown/);assert.match(await p.locator('[data-route="scientist"]').textContent(),/Continue discovery/);
 assert.equal(await p.evaluate(()=>localStorage.getItem('continuum-visited')),'["cells:DNA"]');assert.equal(await p.evaluate(()=>localStorage.getItem('continuum-reflections')),'{"Replace your arm":"same"}');await p.reload();await p.waitForFunction(()=>Journey.getState().sceneReady);assert.equal(await p.evaluate(()=>Journey.getState().route),null);await p.locator('[data-route="futurist"]').click();assert.equal(await p.locator('#progress-label').textContent(),'0 / 6 encounters explored');assert.equal(await p.locator('[data-encounter="1"]').isDisabled(),true);
 await p.locator('#change-route').click();await p.locator('[data-route="scientist"]').click();assert.equal(await p.locator('#progress-label').textContent(),'5 / 5 encounters explored');await p.setViewportSize({width:390,height:844});await p.locator('#approach').click();await p.locator('#undo-pathway').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#confirm-pathway-undo').click();assert.equal(await p.locator('#intro').isVisible(),true);assert.deepEqual(errors,[]);console.log('PASS: pathway-only undo, cancel and Escape safety, child/body reset, chooser labels refreshed, replay locks, reload persistence, other pathways and atlas stores preserved, mobile confirmation.');
}finally{await b.close()}
